application:
  directory:
    input: ${user.home}/data/in
    output: ${user.home}/data/out

  filename:
    toprocess: .dat
    processed: .done.dat

  job:
    scheduler:
      delay: 5000
      interval: 5000