app:
  job:
    scheduler:
      delay: 2000
      interval: 2000

  files:
    directory:
      in: ${user.home}/data/in
      out: ${user.home}/data/out

  filename:
    readonly: .dat
    done: .done.dat

logging:
  level:
    com:
      thamirestissot: DEBUG
